From ubuntu:16.04
ENV MATLAB_VERSION 2018a
MAINTAINER yujmo yujmo94@gmail.com | huua q8046485@163.com
RUN useradd -s /bin/bash -m admin && apt-get update && apt-get install lsb-core net-tools libxt6 supervisor sudo -y
